title : hackathons-2016

safe: true
lsi: false
pygments: false
auto: true

source: .
destination: _deploy 

production_url : https://atagh.github.io/hackathon-2016/

BASE_PATH : https://atagh.github.io/hackathon-2016/
